name: vedb_odometry #WIP, likely will look close to/exactly the same as the environment.yaml for `vedb_store`.
channels:
  - conda-forge
  - phausamann
  - vedb
  - plotly
dependencies:
  - python
  - numpy
  - pandas
  - xarray
  - pupil_recording_interface
  - rigid_body_motion
  - vedb_store
  - plotly
